config/routes.rb
Yeestyle::Application.routes.draw do
  root to: 'home#index'
  get "home/index"

  resources :items
  namespace :admin do 
     resources :items
  end   

end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :itemimg,dependent: :destroy
	scope :withcid,lambda{|cid|where('cid=? and list_time<=? and delist_time>=?',cid,Time.now,Time.now)}
end

app/models/itemimg.rb
class Itemimg < ActiveRecord::Base
	belongs_to :item
end

app/models/taobaokeitem.rb
class Taobaokeitem < ActiveRecord::Base
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	def index
		@items = Item.order('id desc')
	end

    def show
    	@item = Item.find(params[:id])
    end
    
	def new
		@item = Item.new
	end

	def create
		@item = Item.new(params[:item])
		if @item.save
			redirect_to admin_items_path
		else
			render action: 'new'
		end
	end

	def edit
	  @item = Item.find(params[:id])
	end

	def update
	   @item = Item.find(params[:id])
	   if @item.update_attributes(params[:item])
	   	  redirect_to admin_items_path
     	else
     		render action 'edit'
	   	end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to admin_items_path
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@items1 = Item.withcid(50008165)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
  	@item = Item.find(params[:id])
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/items/_form.html.erb
<%=form_for([:admin,@item]) do |f|%>
<div>
  <%=f.label :num_iid %><br/>
  <%=f.text_field :num_iid%>
</div>
<div>
  <%=f.label :title%><br/>
  <%=f.text_field :title%>
</div>
<div>
  <%=f.label :nick%><br/>
  <%=f.text_field :nick%>
</div>
<div>
  <%=f.label :cid%><br/>
  <%=f.text_field :cid%>
</div>
<div>
  <%=f.label :pic_url%><br/>
  <%=f.text_field :pic_url%>
</div>
<div>
  <%=f.label :price%><br/>
  <%=f.text_field :price%>
</div>
<div>
  <%=f.label :list_time%><br/>
  <%=f.date_select :list_time%>
</div>
<div>
  <%=f.label :delist_time%><br/>
  <%=f.date_select :delist_time%>
</div>
<div>
  <%=f.label :location_city%><br/>
  <%=f.text_field :location_city%>
</div>
<div>
  <%=f.label :location_state%><br/>
  <%=f.text_field :location_state%>
</div>

<div>
  <%=f.label :click_url%><br/>
  <%=f.text_field :click_url%>
</div>
<div>
  <%=f.label :shop_click_url%><br/>
  <%=f.text_field :shop_click_url%>
</div>
<div>
	<%=f.submit%>
</div>
<% end %>

app/views/admin/items/edit.html.erb
<h1>Edit Item</h1>
<%=render 'form'%>

app/views/admin/items/index.html.erb
<h1>All Items</h1>
<table>
  <tr>
    <td>Title</td>
    <td>Nick</td>
    <td>Cid</td>
    <td></td>
  </tr>
  <% @items.each do |item|%>
  <tr>
    <td><%=item.title%></td>
    <td><%=item.nick%></td>
    <td><%=item.cid%></td>
    <td><%=link_to 'show',[:admin,item]%>&nbsp
    	<%=link_to 'edit',edit_admin_item_path(item)%>
    	<%=link_to 'delete',[:admin,item],confirm: 'are you sure',method: :delete%></td>
  <% end %>
</table>

<%=link_to 'new',new_admin_item_path%>

app/views/admin/items/new.html.erb
<h1>New Item</h1>
<%=render 'form'%>

app/views/admin/items/show.html.erb
<h1><%=@item.title%></h1>
<%=@item.nick%><br/>
<%=image_tag @item.pic_url%>

app/views/home/index.html.erb
<h1>这是一个亲子导购社区</h1>
<p>即将登场，敬请期待</p>
<div>
  <h2>亲子服装</h2>
  <%@items1.each do |item|%>
    <%=link_to item.title,item%>
    <%=image_tag item.pic_url%>
  <%end%>
</div>

app/views/items/show.html.erb
<h1><%=@item.title%></h1>
<%=@item.nick%><br/>
<%=image_tag @item.pic_url%><br/>
<%=link_to '我要买',@item.click_url,target: 'blank'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yeestyle</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>